### ISSUE TITLE
Bug for expand_mode=0 in latticedb. Should we remove this option anyway?

### ISSUE THREAD

**Issue by Aesku** [yambo-code/yambopy#30]
The issue arises, for example, when calling plot_exciton_2D_ax from YamboExcitonDB. 

For instance, if a 12x12 QE nscf calculation is done, the full BZ should have 144 points, that yambopy reads from the SAVE. In this, YamboExcitonDB.from_db_file calls self.expand_kpoints(expand_mode). If expand_mode == 1, there is no problem. However, if expand_mode == 0, then expand_kpoints creates an extra kpoint and the fullBZ used has 145 points, i.e., K and K' are considered to be different for some reason.

In other words, the function yambopy.dbs.latticedb.expand_kpoints is buggy when expand_mode = 0. Line 195 of latticedb.py

**To reproduce the bug:**
1. In yambopy.dbs.latticedb line 36 impose expand_mode = 0
    def from_db_file(cls,filename='ns.db1',Expand=True,expand_mode=0):
2. From the attached script and SAVE/ns.db1 check that it prints 145. Therefore, functions like plot_exciton_2D_ax do not work.
3. In yambopy.dbs.latticedb line 36 impose expand_mode = 1
   def from_db_file(cls,filename='ns.db1',Expand=True,expand_mode=1):
4. From the attached script and SAVE/ns.db1 check that it prints 144. Everything works as expected.

**Suggestion**

latticedb.py line 200: 
:: expand_mode=0 : k' = S k    [default] --> CHANGE THIS. DEFAULT SHOULD BE 1. expand_mode=0 does not work
[bug.zip](https://github.com/yambo-code/yambopy-devel/files/14110978/bug.zip)

**Comment by palful** [comment]
Removed the `expand_mode` option (kept the correct old `expand_mode=1` as default) in PR #48 .
